name: SuperBros
description: superbros is a creative studio specialised in design and animation
author: superbros
author_email: me@lucabrenna.com
url: http://www.superbros.co.uk

exclude: [config.rb, Gemfile, CNAME, README.md]

navigation_left:
- text: home
  url: /index_dev.html
- text: projects
  url: /projects/index.html
  layout: project

navigation_right:
- text: news
  url: /news/index.html
  layout: news
- text: contact
  url: /contact/index.html
